#!/bin/bash

# DWL startup script

dbus-daemon --session &
eval $(dbus-launch &) && export DBUS_SESSION_BUS_ADDRESS &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst &
clipse -listen
awww-daemon &
emacs --daemon
otd-daemon &
exec ~/.config/dwl/scripts/screenshare-fix.sh &
